# Generated by Django 4.0 on 2022-07-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_comments_id_alter_posts_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
