# Generated by Django 4.0 on 2022-08-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
