# Generated by Django 4.0 on 2022-08-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_feedback_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='mail',
            field=models.CharField(default='no mail', max_length=256),
        ),
    ]
